require 'keener'
require 'vcr'
require 'eventmachine'

# Integration test data
PROJECT_ID = "50e8d5f43843316b28000001"
API_KEY = "b82b029917fa49af84a5827a43e537a7"
COLLECTION_NAME = "votes"

Keener.api_key = API_KEY

VCR.configure do |c|  
  c.cassette_library_dir = 'spec/fixtures/vcr_cassettes'
  c.hook_into :faraday
  c.configure_rspec_metadata!
  
  # Async tests don't work with vcr
  c.allow_http_connections_when_no_cassette = true
end

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  #config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
end

Dir["./spec/support/**/*.rb"].sort.each {|f| require f}